name: Fix Code

on: [push]

jobs:
  fixcode:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      env:
        ACTOR: ${{ secrets.ACTOR }}
        PWD: ${{ secrets.PWD }}
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Run Fix Code
      run: composer run-script fix
    - name: Push Code
      run: composer run-script commit
