name: Fix Code

on: [push]

jobs:
  fixcode:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: Comsenz/fixcode-action@master
      env:
        ACTOR: ${{ secrets.ACTOR }}
        TOKEN: ${{ secrets.TOKEN }}
